const express = require('express'); 
const rootRouter = express.Router(); 
const userRouter = require('./userRoute')
const categoryRouter = require('./categoryRoute')
const courseRouter = require('./courseRoute')
const enrollmentRouter = require('./enrollmentRoute')
const levelRouter = require('./LevelRoute')
const reviewRouter = require('./reviewRouter')
const sectionRouter = require('./sectionRoute')
const videoRouter = require('./videoRouter')
const videoCompletedRouter = require('./videoCompletedRoute')
const quizzeRouter = require('./quizzeRoute')
const questionRouter = require('./questionRouter')
const answerRouter = require('./answerRoute')
const userSubmitRouter = require('./userSubmitRouter')
const orderRouter = require('./orderRouter')
const cartRoute = require('./cartRoute')

rootRouter.use('/users', userRouter)
rootRouter.use('/categories', categoryRouter)
rootRouter.use('/courses', courseRouter)
rootRouter.use('/enrollments', enrollmentRouter)
rootRouter.use('/levels', levelRouter)
rootRouter.use('/reviews', reviewRouter)
rootRouter.use('/sections', sectionRouter)
rootRouter.use('/videos', videoRouter)
rootRouter.use('/videoCompleted', videoCompletedRouter)
rootRouter.use('/quizzes', quizzeRouter)
rootRouter.use('/questions',questionRouter)
rootRouter.use('/answers', answerRouter)
rootRouter.use('/userSubmits', userSubmitRouter)
rootRouter.use('/orders', orderRouter)
rootRouter.use('/carts', cartRoute)

module.exports = rootRouter